name: build Windows

on:
  push:

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with: { python-version: 3.9 }

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install PyInstaller Pillow pycryptodome
              

      - name: build
        run: pyinstaller ./lina/lina.py --onefile

      - name: Upload 
        uses: actions/upload-artifact@v2
        with:
          name: lina-windows.exe
          path: dist/lina.exe
